const HOSPITAL_ACTION_TYPES = {
  GET_HOSPITALDETAILS: "GET_HOSPITALDETAILS",
  FETCH_HOSPITAL_DETAILS_START: "FETCH_HOSPITAL_DETAILS_START",
  FETCH_HOSPITAL_DETAILS_SUCCESS: "FETCH_HOSPITAL_DETAILS_SUCCESS",
  FETCH_HOSPITAL_DETAILS_FAILURE: "FETCH_HOSPITAL_DETAILS_FAILURE",
  SET_HOSPITAL_COORDINATES: "SET_HOSPITAL_COORDINATES",
};

export default HOSPITAL_ACTION_TYPES;
